### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by antiburen** [sn0b4ll/aria2-onion-downloader#1]
Hi, I installed it and joined joined both with the secret, when I try to download a file says: 

```
Task Status: Error Occurred (17) fallocate failed. cause: not supported
Error Description: Filesystem error occurred.
```

What can be the issue? It is a GZ file on a onion domain.

**Comment by antiburen** [comment]
problem with the windows shared directory.

**Comment by luishugoooo** [comment]
did you find a fix?
