### ISSUE TITLE
Set rpc url

### ISSUE THREAD

**Issue by Motophan** [sn0b4ll/aria2-onion-downloader#11]
![WsRryXU](https://github.com/sn0b4ll/aria2-onion-downloader/assets/42502676/4c080123-409b-4250-9113-30f9276d5511)
My rpc is running on 127.0.0.1:6800 not the fqdn:6800

I cant figure out how to set this explicitly

Can you set a enviroment var that it will respect

like
```
    environment:
      - RPCPORT=6800
```
add
```
    environment:
      - RPCHOST=127.0.0.1

```

**Comment by Motophan** [comment]
Also, /etc/tor/torrc
```
Log notice file /var/log/tor/log
RunAsDaemon 1
DataDirectory /var/lib/tor
HiddenServiceDir /var/lib/tor/nginx/
HiddenServicePort 80 unix:/var/run/hidden_nginx.sock
HiddenServicePort 6800 127.0.0.1:6800
HiddenServicePort 8080 127.0.0.1:8080
```
Ive tried both using nginx on :80 with proxypass to 127.0.0.1:8080 and using .onion:8080 and this also does not work.

**Comment by sn0b4ll** [comment]
Hey @Motophan, many thanks for using the tool.

Actually you don't have to specify the RPC Port of Tor, but of the Aria2 downloader.

I hope that helps :) If not, please give me another ping. If not, I will close the issues in a couple of days.

Greetings,
sn0b4ll
