### ISSUE TITLE
"/conf/nginx.conf" failed

### ISSUE THREAD

**Issue by DepHedge** [sn0b4ll/aria2-onion-downloader#15]
nginx: [emerg] open() "/conf/nginx.conf" failed (2: No such file or directory)

**Comment by reece394** [comment]
Never seen this error before. Can you tell me what you are attempting to run it on? Hardware, Operating system, Version of Docker etc... 
When running on Windows 10 with WSL and macOS with the latest versions of Docker everything works fine for me.

**Comment by reece394** [comment]
Seems like a permissions issue with what you are using as per [here ](https://github.com/nginxinc/docker-nginx/issues/494)

**Comment by sn0b4ll** [comment]
@DepHedge, did @reece394 comment help?
