### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by LiaoLongPing** [sn0b4ll/aria2-onion-downloader#16]
aria2-onion-downloader-main-downloader-1  | 2024/01/13 19:59:07 [Warning] [44122108] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > read tcp 127.0.0.6:59265->127.0.0.1:9050: i/o timeout
aria2-onion-downloader-main-downloader-1  | 2024/01/13 19:59:07 [Warning] [44122108] proxy/http: failed to read response from 6qubpgkb7vjd6upivya4ll2xvzkx6zdj5bfwfo7qqm4jd3cuv4nwg2id.onion > io: read/write on closed pipe
aria2-onion-downloader-main-downloader-1  | 2024/01/13 19:59:07 [Warning] [44122108] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:16001->127.0.0.1:44646: write: broken pipe

**Comment by sn0b4ll** [comment]
Hey @LiaoLongPing please retry with the current version. Sometimes certain threats fail, that's normal - were you still able to finish the download?
