### ISSUE TITLE
Detailed Installation

### ISSUE THREAD

**Issue by TheYoungestVI** [sn0b4ll/aria2-onion-downloader#17]
Good evening, 

I hope this message finds you well. I am impressed by the functionality and features this program offers, and I am eager to give it a try.

However, I have encountered some difficulties during the installation process and was hoping you could provide more detailed and specific installation instructions. I understand that creating comprehensive documentation can be time-consuming, but having clear instructions would greatly help users like myself who may be encountering challenges.

I understand that you may have limited time, and I truly appreciate the effort you've put into developing this project. I am more than willing to contribute to the documentation or assist in any way that would make this process smoother for other users as well.

Thank you very much for your time and consideration. I look forward to your response and appreciate your dedication to maintaining an open-source project.

**Comment by sn0b4ll** [comment]
Hey @TheYoungestVI,

Many thanks on your feedback.

Can you please describe at which point in the [Usage](https://github.com/sn0b4ll/aria2-onion-downloader?tab=readme-ov-file#usage) section of the readme you got stuck / you would like to have additions?
