### ISSUE TITLE
Auto restart failed downloads

### ISSUE THREAD

**Issue by keldnorman** [sn0b4ll/aria2-onion-downloader#2]
Could it be possible to make the download auto restart if it fails ? I just tested this project ( it's awesome! ) but i have to manually restart a lot of downloads every morning.

**Comment by astandarduser** [comment]
Works great, but + 1 on this issue. Would love a fix

**Comment by sn0b4ll** [comment]
Hey people, sorry for the very late response. 

Sadly this is something which would have to come out of aria2 :/ I am just patching tor and aria together. There are already a couple of "retry XYZ" issues open over there, so I would not like to open another one but also I am currently unable to work on it myself. Sorry for that :/
