### ISSUE TITLE
[Question] Updating url of a downloading task

### ISSUE THREAD

**Issue by amaillo-coop** [sn0b4ll/aria2-onion-downloader#22]
This downloader works beautifully, thanks a lot for sharing it!

I would like to know if it's possible to change the url of a current downloading task.
I need to change all tasks to a new mirror because actual domain is down.

Thanks in advance!

**Comment by sn0b4ll** [comment]
Hey @amaillo-coop,

Happy to hear this and sorry for the late response.

Sadly I don't know of a possibility in Aria2, but I  imagine you could do this by manipulating the /etc/host-file on the downloader and overwriting the old domain with the new one. But tbh that is kinda hacky.
