### ISSUE TITLE
Can i download a normal file without using TOR?

### ISSUE THREAD

**Issue by shidevil** [sn0b4ll/aria2-onion-downloader#23]
Hi @sn0b4ll ,

I love this project alot. I just want to check if i were to download a normal file such as https://releases.ubuntu.com/24.04/ubuntu-24.04-desktop-amd64.iso

Will it be using TOR? can it route to normal traffic if the url is not from a .onion domain? 

Thank you

**Comment by sn0b4ll** [comment]
Hey @shidevil,

this downloader will always use Tor to connect to the internet and there also download clear-net files like the one stated via Tor.

But you can simply use aria2 (https://aria2.github.io/) itself to download files without tor 😊
