### ISSUE TITLE
Tor network not used to download.

### ISSUE THREAD

**Issue by Prashanth-BC** [sn0b4ll/aria2-onion-downloader#24]
Try downloading the the web page https://check.torproject.org. The downloaded page (index.html) in the download folder shows the actual ip with the message not using TOR. This implies tor network is not used to access the web page. Any idea why this is happening?

**Comment by BlindAndInsane** [comment]
ya same

**Comment by and5302** [comment]
hello sir i also got an error while trying to run the docker file in terminal and that is

726.9 + echo 'installed: /usr/local/lib/v2ray/geoip.dat'
726.9 installed: /usr/local/lib/v2ray/geoip.dat
726.9 + echo 'installed: /usr/local/lib/v2ray/geosite.dat'
726.9 installed: /usr/local/lib/v2ray/geosite.dat
726.9 + rm -r /tmp/tmp.oaPBON/
726.9 + echo 'removed: /tmp/tmp.oaPBON/'
726.9 removed: /tmp/tmp.oaPBON/
726.9 + echo 'You may need to execute a command to remove dependent software: apk del curl unzip'
726.9 You may need to execute a command to remove dependent software: apk del curl unzip
726.9 + echo 'info: V2Ray is installed.'
726.9 info: V2Ray is installed.
726.9 Cloning into '/home/aria2'...
778.7 error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
778.7 error: 3425 bytes of body are still expected
778.8 fetch-pack: unexpected disconnect while reading sideband packet
778.8 fatal: early EOF
778.8 fatal: fetch-pack: invalid index-pack output
------
failed to solve: process "/bin/sh -c apk add --update --no-cache bash tor tzdata vim autoconf build-base git libgcc gmp libtool gnutls gnutls-dev nettle libssh2 libssh2-dev ca-certificates c-ares c-ares-dev libxml2 libxml2-dev sqlite-libs sqlite-dev automake cppunit cppunit-dev util-macros gettext gettext-dev zlib zlib-dev curl unzip && /home/install-release.sh && git clone https://github.com/aria2/aria2.git /home/aria2 && patch /home/aria2/src/HttpSkipResponseCommand.cc < /home/500retry.patch && patch /home/aria2/src/DownloadCommand.cc < /home/slowretry.patch && patch /home/aria2/src/OptionHandlerFactory.cc < /home/removeconnlimit.patch && patch /home/aria2/src/SocketBuffer.cc < /home/connclosed.patch && rm -f /home/500retry.patch && rm -f /home/slowretry.patch && rm -f /home/removeconnlimit.patch && rm -f /home/connclosed.patch && rm -f /home/install-release.sh && cd /home/aria2 && autoreconf -i && ./configure && make -j`nproc` && make install && rm -rf /home/aria2 && apk del autoconf build-base git libtool gnutls-dev libssh2-dev c-ares-dev libxml2-dev sqlite-dev automake cppunit-dev util-macros gettext-dev zlib-dev curl unzip && apk add --update --no-cache python3 py3-stem && cd /home && mkdir creatorrc && cd /home/creatorrc && aria2c https://raw.githubusercontent.com/hephaest0s/creatorrc/master/creatorrc.py && aria2c https://raw.githubusercontent.com/hephaest0s/creatorrc/master/guard_country_resolver.py" did not complete successfully: exit code: 128

**Comment by sn0b4ll** [comment]
@Prashanth-BC sorry for the late response. TBH this is not the use-case of this tool - the use-case is to download files from a .onion domain faster, no download files from the "clearnet" via tor. But yeah, I can verify that downloads from the clear text are currently not being done via tor, which one might expect at first. Sadly I currently don't have the time to implement this, but will open a feature request for the future. Closing for now as "expected behavior".

@and5302 some security solutions block the download of the creatorrc files, please make sure you are not in a protected network. I had the same problem when I had an IPS activated, which blocked the file. Sadly not fixable from project side.
