### ISSUE TITLE
Not resuming after error 500

### ISSUE THREAD

**Issue by Emen0s** [sn0b4ll/aria2-onion-downloader#4]
Hello !
I realize that the differents download threads are closing after some time and not resuming when they encounter an error 500.

aria2-onion-downloader-main-downloader-1  |   -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=500

I have to reload the downloader container to force aria2 into resuming all the threads before they reach zero.

The issue was found with different error codes in aria2, and is pretty easy to patch int he file "b/src/HttpSkipResponseCommand.cc", see : 
https://github.com/aria2/aria2/issues/1229

I think Aria2 should try resuming the download whateven the error code is, after some time secified by the user.

Thank you for this wonderfull tool by the way !
Hope it helps :)

**Comment by simonhuwiler** [comment]
Hi Lk4rma
Have you found a way to implement this?

**Comment by sn0b4ll** [comment]
@Lk4rma my pleasure, I am happy you like it!

Sadly currently this project is pretty simply installing the current version of aria2 out of the alpine repos without further customizing it. Compiling aria2 would be an option, but currently I sadly don't have the bandwith to extend the dockerfile to do that. The other way would be to include the patch in aria2 iteself - with that, and as soon as the new file would be in the alpine repos, this would also be fixed.

Maybe one of these options works for you. I would close this for now.

**Comment by simonhuwiler** [comment]
For completeness: This way my workaround:
Under `Aria2 Settings -> Advanced Settings` change:
* `Allow Overwrite` to `True`
* `Auto File Renaming` to `False`

Then
* add all your files to the download queue
* Go to `Aria2 Status` and press `Save Session` (important!)

This will resume the settings and downloads the next time you open it.

Then I wrote a Python script that restarts the Docker container every 30 minutes. Of course you can also do this with a shell script.

```python
import time, os, datetime

while True:
    time.sleep(60 * 30)
    print(datetime.datetime.now())
    os.system("docker-compose restart")
```

It worked with that. Great project, thank you!

**Comment by sn0b4ll** [comment]
That's great, many thanks for sharing!
